version: "3"

services:
  mysql-starbucks:
    image: mysql:8.0
    volumes:
      - /tmp:/tmp
    networks:
      - starbucks-api-network
    ports:
      - 3306
    environment:
      MYSQL_USER: starbucks-user
      MYSQL_PASSWORD: starbucks-password
      MYSQL_DATABASE: db_starbucks
      MYSQL_ROOT_PASSWORD: cmpe172
    restart: always
  starbucks-api:
    image: rustypedrosa/starbucks-api:v4
    depends_on:
    - mysql-starbucks
    volumes:
      - /tmp:/tmp
    networks:
      - starbucks-api-network
    ports:
      - 8080
    environment:
      MYSQL_HOST: "mysql-starbucks"
    restart: always
  kong:
    image: kong:2.4.0
    depends_on:
    - starbucks-api
    ports:
    - "80:8000"
    - "443:8443"
    - "8036:3306"
    - "3306:3306"
    - "8001:8001"
    - "8444:8444"
    environment:
      KONG_DATABASE: "off"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
      LOG_LEVEL: "info"
    networks:
      - starbucks-api-network

volumes:
  schemas:
    external: false

networks:
  starbucks-api-network:
    name: starbucks-api-network
    driver: bridge
